// Generated by CoffeeScript 2.1.0
(function() {
  var digPow;

  digPow = function(n, p) {
    var count, final, sum, tempArr;
    count = 0;
    sum = 0;
    final = 0;
    tempArr = [];
    tempArr = ("" + n).split('');
    while (count < tempArr.length) {
      sum += Math.pow(parseInt(tempArr[count]), p + count);
      count++;
    }
    if (sum % n === 0) {
      return final = sum / n;
    } else {
      return -1;
    }
  };

  console.log(digPow(89, 1));

}).call(this);
