// Generated by CoffeeScript 2.1.0
(function() {
  //# race condtions##
  var tortoiseRacing;

  tortoiseRacing = function(speedA, speedB, disCovered) {
    var diff, results, time, timeMins, timeSecs, timeX;
    results = [];
    console.log(disCovered);
    diff = speedA - speedB;
    console.log(diff);
    time = disCovered / diff;
    timeX = disCovered % diff;
    console.log(timeX);
    timeMins = time * 60;
    timeSecs = timeX * 60;
    return console.log({time, timeMins, timeSecs});
  };

  tortoiseRacing(850, 720, 70);

}).call(this);

//# sourceMappingURL=25_1.js.map
