// Generated by CoffeeScript 2.1.0
(function() {
  var findOccurenceOf, findOccurenceOf3, getAllStudents, getModifiedStudents, getNumbersDivisibleBy11, getNumbersDivisibleByNumber, getOnlyAStudents, getOnlyEventStudents, getSortedNumbers, numbers, printAllStudents, students;

  students = [
    {
      id: 1,
      firstname: 'Tuhin',
      lastname: 'Banerjee'
    },
    {
      id: 2,
      firstname: 'Alias',
      lastname: 'Domain'
    },
    {
      id: 3,
      firstname: 'Alice',
      lastname: 'Kulter'
    },
    {
      id: 4,
      firstname: 'Monkey',
      lastname: 'Charm'
    }
  ];

  printAllStudents = function(student) {
    return console.log(`Student : ${student.firstname} ${student.lastname} has id of ${student.id}`);
  };

  getAllStudents = function() {
    var i, len, results, student;
    results = [];
    for (i = 0, len = students.length; i < len; i++) {
      student = students[i];
      results.push(printAllStudents(student));
    }
    return results;
  };

  getOnlyEventStudents = function() {
    var i, len, results, student;
    results = [];
    for (i = 0, len = students.length; i < len; i += 2) {
      student = students[i];
      results.push(printAllStudents(student));
    }
    return results;
  };

  getModifiedStudents = function() {
    var result, student;
    result = (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = students.length; i < len; i++) {
        student = students[i];
        results.push((printAllStudents(student)) + ' : Wonder School');
      }
      return results;
    })();
    return console.log(result);
  };

  getOnlyAStudents = function() {
    var i, len, results, student;
    results = [];
    for (i = 0, len = students.length; i < len; i++) {
      student = students[i];
      if (student.firstname[0] = 'A') {
        results.push(printAllStudents(student));
      }
    }
    return results;
  };

  numbers = [3, 2, 45, 55, 1, 3, 444, 2, 44, 33, 8.99];

  getSortedNumbers = function() {
    return console.log(numbers.sort(function(a, b) {
      return a - b; //this will return positive , negative or 0 based on sorted comparison.
    }));
  };

  getNumbersDivisibleByNumber = function(testfunc) {
    var number, result;
    result = (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = numbers.length; i < len; i++) {
        number = numbers[i];
        if (testfunc(number)) {
          results.push(number);
        }
      }
      return results;
    })();
    return console.log(result);
  };

  getNumbersDivisibleBy11 = function() {
    return getNumbersDivisibleByNumber(function(n) {
      return n % 11 === 0;
    });
  };

  findOccurenceOf = function(numberx) {
    var count, i, len, num;
    count = 0;
    for (i = 0, len = numbers.length; i < len; i++) {
      num = numbers[i];
      if (num === 3) {
        count++;
      }
    }
    return console.log(count);
  };

  findOccurenceOf3 = function() {
    return findOccurenceOf(3);
  };

  
  //getAllStudents()
  //console.log '======================='
  //getOnlyAStudents()
  //console.log '======================='
  //getOnlyEventStudents()
  //console.log '======================='
  //getModifiedStudents()
  //getSortedNumbers()
  //getNumbersDivisibleBy11()
  findOccurenceOf3();

}).call(this);
