// Generated by CoffeeScript 2.1.0
(function() {
  var Joe, Students, func, getTotalMarks, marks, totalmarks;

  Students = class Students {
    constructor(id, firstname, lastname, number) {
      this.myName = this.myName.bind(this);
      this.id = id;
      this.firstname = firstname;
      this.lastname = lastname;
      this.totalSubject = number;
    }

    printStudentDetails() {
      return `${this.firstname} ${this.lastname} has id of ${this.id} and total Subject : ${this.totalSubject} `;
    }

    toString() {
      return this.printStudentDetails();
    }

    myName() {
      return console.log(`${this.firstname}`);
    }

  };

  getTotalMarks = function(marks) {
    return marks.reduce(function(t, n) {
      return t + n;
    });
  };

  Joe = new Students('001', 'Joe', 'Bhadra', 5);

  marks = [45, 35, 22, 77, 88, 55];

  totalmarks = getTotalMarks(marks);

  //console.log  "#{new Students('001','Joe','Bhadra',5)}  + With total Marks #{totalmarks}"
  Joe.myName();

  func = function(callback) {
    return callback();
  };

  func(Joe.myName);

}).call(this);
