// Generated by CoffeeScript 2.1.0
(function() {
  var wrapText;

  wrapText = function(mainText, maxline = 10, endToken = '\n') {
    var words;
    words = mainText.split(' ');
    return console.log(words[0].toUpperCase() + words.slice(1).join('_'));
  };

  //  console.log words
  wrapText("kasma mdadmamdamapm dmadmamdm adamdam dadadpamdap");

}).call(this);
