// Generated by CoffeeScript 2.1.0
(function() {
  //Define some constants
  var TIME_IN_ONE_DAY, TIME_IN_ONE_HOUR, TIME_IN_ONE_MIN, TIME_IN_ONE_SEC, dateDifference;

  TIME_IN_ONE_SEC = 1000;

  TIME_IN_ONE_MIN = TIME_IN_ONE_SEC * 60;

  TIME_IN_ONE_HOUR = TIME_IN_ONE_MIN * 60;

  TIME_IN_ONE_DAY = TIME_IN_ONE_HOUR * 24;

  dateDifference = function(startDate, endDate, units = 'Days') {
    var elpased;
    elpased = endDate - startDate;
    console.log(elpased);
    console.log(units);
    switch (units) {
      case 'Days':
        console.log(TIME_IN_ONE_DAY);
        return elpased / TIME_IN_ONE_DAY;
      case 'Mins':
        return elpased / TIME_IN_ONE_MIN;
    }
  };

  module.exports = {
    findDateDiff: dateDifference
  };

}).call(this);

//# sourceMappingURL=PlayWithDates.js.map
