// Generated by CoffeeScript 2.1.0
(function() {
  var convertBase, convertBase10, convertBase2;

  convertBase = function(number, fromBase, toBase) {
    var value;
    value = parseInt(number, fromBase);
    return value.toString(toBase);
  };

  convertBase2 = function(number, fromBase = 10) {
    return convertBase(number, fromBase, 2);
  };

  convertBase10 = function(number, fromBase = 2) {
    return convertBase(number, fromBase, 10);
  };

  module.exports = {
    convertToBase: convertBase,
    convertToBase2: convertBase2,
    convertToBase10: convertBase10
  };

}).call(this);
